name: Pylint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analyzing the code with pylint
      run: |
        pylint --function-naming-style="camelCase" --method-naming-style="camelCase" $(git ls-files './leblad/*.py')
        pylint --function-naming-style="camelCase" --method-naming-style="camelCase" $(git ls-files './tests/*.py')
    - name: Run test
      run: |
        python -m unittest tests/test_index.py
